### ISSUE TITLE
Error during decoding

### ISSUE THREAD

**Issue by moramatteo** [bitonic/wadump#4]
The script crashes when trying to decode a message where the quoted message is of type 'location'.

Console error: Script snippet no. 1:287 could not decode message _"message id"_ unimplemented wire type 1

**Comment by bitonic** [comment]
These are probably "lat" and "lng" fields, I'll add the wire type decoding.

**Comment by bitonic** [comment]
https://github.com/bitonic/wadump/commit/0121931ca082bced1aedfe671b49f377380893f6 should fix it, can you test?

**Comment by moramatteo** [comment]
Sorry, but it still doesn't work.

New console error from line 329:
could not decode message _"message id"_ unimplemented wire type 0

**Comment by bitonic** [comment]
91e9be9e15111b1c1ef71b5a1727312f4ce6aff3 should fix _that_, could you try again?

**Comment by moramatteo** [comment]
I confirm that now it works properly.
Thank you very much
